### ISSUE TITLE
Remove parameters that only add complexity

### ISSUE THREAD

**Issue by DecentralizedDan** [interlock-network/interlock-models#15]
For example, Scam Success Rate is influenced by Scam Page View Rate
* This could be simplified by just having Scam Success Rate by itself

**Comment by galactic-beyond** [comment]
So, technically correct, but the page-views are used elsewhere in the model (not show on graph -- specifically, they influence airlock-lookups). Should either make this relationship explicit/formal, or should find different way to model/drive airlock-lookups.
