### ISSUE TITLE
Create Model 1-Pagers

### ISSUE THREAD

**Issue by galactic-beyond** [interlock-network/interlock-models#23]
Have detailed, hyper-linked "paper"-like entity that walks people through the model, presents charts, and inputs/outputs, and provides justification for decisions and assumptions.

**Comment by DecentralizedDan** [comment]
This will be a minimum of 10 charts and a maximum of 30 charts with up to a paragraph of text each to explain.

**Comment by galactic-beyond** [comment]
Started creating these in the `docs/shorts` directory. Will be ongoing process.
